### ISSUE TITLE
Error when run " luarocks make tfluids-1-00.rockspec"

### ISSUE THREAD

**Issue by suzhiba** [google/FluidNet#10]
Dear Sir/Madam,
I met a error when I run " luarocks make tfluids-1-00.rockspec". I dont know what the problem is. Output didnt show the reason. I need your help. Thanks. 
Driver Version: 375.88  CUDA7.5/8 gcc4.8 ubuntu14.04 cmake3.2 Tesla K40
`-- Found Torch7 in /home/roseyu/su/distro/install
-- Compiling with OpenMP support
Compiling for CUDA architecture 3.5
Compiling with OpenGL support
Compiling with CUDA support.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/roseyu/FliudNet/FluidNet/torch/tfluids/build
[ 33%] Building NVCC (Device) object CMakeFiles/tfluids.dir/generic/tfluids_generated_tfluids.cu.o
/home/roseyu/FliudNet/FluidNet/torch/tfluids/generic/tfluids.cu(1882): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00008763_00000000-7_tfluids.cpp1.ii".
CMake Error at tfluids_generated_tfluids.cu.o.cmake:266 (message):
  Error generating file
  /home/roseyu/FliudNet/FluidNet/torch/tfluids/build/CMakeFiles/tfluids.dir/generic/./tfluids_generated_tfluids.cu.o

make[2]: *** [CMakeFiles/tfluids.dir/generic/tfluids_generated_tfluids.cu.o] Error 1
make[1]: *** [CMakeFiles/tfluids.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.`

**Comment by jonathantompson** [comment]
hmmmmmmm....

I just pulled the repo and it compiles OK for me (see output below).
However, it's likely that I have an old version of Torch installed.

tfluids.cu line 1882 is:

THCudaTensor_norm(state, tensor_p_delta_norm, tensor_p_delta, 2, 1);

You might want to look into whether or not torch's C API has changed
(because this is a function outside of my codebase).  Sorry, I don't have
time to check this for you, you'll have to do some digging yourself.  Or
roll back cutorch to the commit I have installed
(SHA: 7112d9e722f067eac298692dd06d79f1f3cdb90a).




-- Build files have been written to:
/usr/local/google/home/tompson/Documents/FluidNet/torch/tfluids/build
[ 33%] Building NVCC (Device) object
CMakeFiles/tfluids.dir/generic/./tfluids_generated_tfluids.cu.o
[ 66%] Building NVCC (Device) object
CMakeFiles/tfluids.dir//./tfluids_generated_init.cu.o
Scanning dependencies of target tfluids
[100%] Building CXX object CMakeFiles/tfluids.dir/generic/advect_type.cc.o
Linking CXX shared module libtfluids.so
[100%] Built target tfluids
cd build && make install
-- Found Torch7 in /usr/local/google/home/tompson/torch/install
-- Compiling with OpenMP support
Compiling for CUDA architecture 3.5
Compiling with OpenGL support
Compiling with CUDA support.
-- Configuring done
-- Generating done
-- Build files have been written to:
/usr/local/google/home/tompson/Documents/FluidNet/torch/tfluids/build
Linking CXX shared module libtfluids.so
[100%] Built target tfluids
Install the project...
-- Install configuration: "Release"
-- Installing:
/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks/tfluids/1-00/lib/libtfluids.so
-- Set runtime path of
"/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks/tfluids/1-00/lib/libtfluids.so"
to
"$ORIGIN/../lib:/usr/local/google/home/tompson/torch/install/lib:/usr/local/cuda/lib64:/opt/OpenBLAS/lib"
-- Installing:
/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks/tfluids/1-00/lua/tfluids/init.lua
-- Installing:
/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks/tfluids/1-00/lua/tfluids/flags_to_occupancy.lua
-- Installing:
/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks/tfluids/1-00/lua/tfluids/set_wall_bcs.lua
-- Installing:
/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks/tfluids/1-00/lua/tfluids/test_tfluids.lua
-- Installing:
/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks/tfluids/1-00/lua/tfluids/velocity_divergence.lua
-- Installing:
/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks/tfluids/1-00/lua/tfluids/velocity_update.lua
-- Installing:
/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks/tfluids/1-00/lua/tfluids/volumetric_up_sampling_nearest.lua
Updating manifest for
/usr/local/google/home/tompson/torch/install/lib/luarocks/rocks
tfluids 1-00 is now built and installed in
/usr/local/google/home/tompson/torch/install/ (license: Apache V2.0)

**Comment by 2chaos** [comment]
Hello, I have encountered the same problem as you. Have you solved it now? I searched the Internet for this question. There was a suggestion to change cudnn6.0 to cudnn5.1. I did, but it didn't work. So I want to know if you have any good way. Thank you very much。

**Comment by jonathantompson** [comment]
Sorry for the slow reply to this. Fixed.
